// SIGN UP USER
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

// AUTO SIGN_IN
export const AUTO_SIGN_IN_SUCCESSFUL = 'AUTO_SIGN_IN_SUCCESSFUL'
export const AUTO_SIGN_IN_FAIL = 'AUTO_SIGN_IN_FAIL'

//USER SIGN_IN
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'

// USER LOGOUT
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL'
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL'

// CLEAR_NOTIFICATIONS
export const CLEAR_NOTIFICATIONS='CLEAR_NOTIFICATIONS'

// LOAD DATA
export const LOAD_SUCCESSFUL = 'LOAD_SUCCESSFUL'
export const LOAD_FAIL = 'LOAD_FAIL'

// FETCH PUBLIC EVENTS
export const FETCH_PUBLIC_EVENTS_SUCCESS = 'FETCH_PUBLIC_EVENTS_SUCCESS'
export const FETCH_PUBLIC_EVENTS_FAIL = 'FETCH_PUBLIC_EVENTS_FAIL'

export const FILTER_CATEORY = 'FILTER_CATEORY'

export const REMOVE_FILTER_CATEORY = 'REMOVE_FILTER_CATEORY'

export const INTERESTED_EVENT_SUCCESS = 'INTERESTED_EVENT_SUCCESS'
export const INTERESTED_EVENT_FAILURE = 'INTERESTED_EVENT_FAILURE'

export const ACCEPT_DECLINE_SUCCESS = 'ACCEPT_DECLINE_SUCCESS'
export const ACCEPT_DECLINE_FAIL = 'ACCEPT_DECLINE_FAIL'

export const CHECK_INTERESTED_SUCCESS = 'CHECK_INTERESTED_SUCCESS'
export const CHECK_INTERESTED_FAIL = 'CHECK_INTERESTED_FAIL'

export const FETCH_PRIVATE_EVENTS_SUCCESS = 'FETCH_PRIVATE_EVENTS_SUCCESS'
export const FETCH_PRIVATE_EVENTS_FAIL = 'FETCH_PRIVATE_EVENTS_FAIL'

export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIl'


