// SIGN UP USER
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

// AUTO SIGN_IN
export const AUTO_SIGN_IN_SUCCESSFUL = 'AUTO_SIGN_IN_SUCCESSFUL'
export const AUTO_SIGN_IN_FAIL = 'AUTO_SIGN_IN_FAIL'

//USER SIGN_IN
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'

// USER LOGOUT
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL'
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL'

// CLEAR_NOTIFICATIONS
export const CLEAR_NOTIFICATIONS='CLEAR_NOTIFICATIONS'

// LOAD DATA
export const LOAD_SUCCESSFUL = 'LOAD_SUCCESSFUL'
export const LOAD_FAIL = 'LOAD_FAIL'


